jenkinsfile: "pipeline {\r\n    agent any\r\n    environment {\r\n        // Define\
  \ the build tool and scan tool as environment variables\r\n        BUILD_TOOL =\
  \ 'Maven'\r\n        SCAN_TOOL = 'SonarQube'\r\n    }\r\n    stages {\r\n      \
  \  stage('Build') {\r\n            steps {\r\n                script {\r\n     \
  \               // Print out the build tool being used\r\n                    echo\
  \ \"Using build tool: ${env.BUILD_TOOL}\"\r\n                }\r\n             \
  \   // Actual build step using Maven\r\n                sh 'mvn clean package'\r\
  \n            }\r\n        }\r\n        stage('Test') {\r\n            steps {\r\
  \n                script {\r\n                    // Print out the build tool being\
  \ used during testing\r\n                    echo \"Using build tool: ${env.BUILD_TOOL}\"\
  \r\n                }\r\n                // Actual test step using Maven\r\n   \
  \             sh 'mvn test'\r\n            }\r\n        }\r\n        stage('SonarQube\
  \ Scan') {\r\n            steps {\r\n                script {\r\n              \
  \      // Print out the scan tool being used\r\n                    echo \"Using\
  \ scan tool: ${env.SCAN_TOOL}\"\r\n                }\r\n                // SonarQube\
  \ analysis step\r\n                withSonarQubeEnv('MySonarQubeServer') {\r\n \
  \                   sh 'mvn sonar:sonar'\r\n                }\r\n            }\r\
  \n        }\r\n        stage('Deploy') {\r\n            steps {\r\n            \
  \    script {\r\n                    // Print out the build tool during deployment\r\
  \n                    echo \"Using build tool: ${env.BUILD_TOOL}\"\r\n         \
  \       }\r\n                // Deployment step (this could be using SCP or any\
  \ other method)\r\n                sh 'scp target/artifact-1.0.0.jar user@server:/path/to/deploy'\r\
  \n            }\r\n        }\r\n    }\r\n}\r\n"
